### PR TITLE
1183 Words Turkish Translated

### PR DESCRIPTION
**Pull request by grafiktr**

### CODE REVIEW

**Comment by caabernathy** [comment]
Hey, you'll want to follow the directions here to get translation going - https://docusaurus.io/docs/en/translation.html#translating-your-existing-docs

**Comment by JoelMarcey** [comment]
And if you want some sample files to help guide you, you can follow the instructions here: https://docusaurus.io/docs/en/translation.html#docusaurus-translation-configurations

**Comment by grafiktr** [comment]
@caabernathy unfortunately, i am lack of those technical skills and informations to do so, but i downloaded the translation to CrowdIn directly. Would you mind if i ask you to download the projects directly to CrowdIn so I can work better and be more effective.

**Comment by yangshun** [comment]
Thanks for your PR! Sorry, but we'll be closing this as this doesn't seem to be what we need/want.

**Pull request closed without merging**
