### PR TITLE
Update 02-Icebreaker.md

### PR DESCRIPTION
**Pull request by sbansal3096**

### CODE REVIEW

**Comment by yangshun** [comment]
@sbansal3096 Please sign the CLA first 😄

**Comment by sbansal3096** [comment]
@yangshun Done :dancing_men:

**Comment by yangshun** [comment]
Nice self introduction! 🎉

In future, use more self-descriptive commit messages. I changed it to "Add Shubham introduction", which is more meaningful than "Update Spellcheck-02.md".

**Comment by JoelMarcey** [comment]
Thanks @sbansal3096!

> I love watching football. 

I assume you mean what we call soccer in the United States. I like both soccer (futbol) and American football. 😄

**Comment by sbansal3096** [comment]
@joelmarcey yeah right! It's called soccer in America ⚽

**Pull request merged**
