### PR TITLE
Add website deploy to CI

### PR DESCRIPTION
**Pull request by caabernathy**
Adding the website deployment to the Circle CI config.

### CODE REVIEW

**Comment by caabernathy** [comment]
I just tested the config.yml but not a build since I didn't know if I could test a deploy locally.

**Comment by JoelMarcey** [comment]
How do you test the `config.yml`?

**Comment by caabernathy** [comment]
`$ circleci config validate -c .circleci/config.yml`

Also you need to install something Docker-related, see https://circleci.com/docs/2.0/test/

**Comment by JoelMarcey** [comment]
TIL - thank you!

**Comment by caabernathy** [comment]
I'm currently checking the Circle CI logs and wondering why both jobs didn't run - for deploying the website and running tests.

**Comment by caabernathy** [comment]
Perhaps I'll merge it in and see if it works after that.

**Comment by JoelMarcey** [comment]
Did it end up working after the merge?

**Pull request merged**
